public enum CommonMsgID
{
	COMMON_ERRORMESSAGE = 901,
	COMMON_LOGGER_INIT = 902,
	COMMON_CLUSTERSERVER_INIT = 903,
	COMMON_CLUSTERCLIENT_INIT = 904,
	COMMON_CLUSTERCLIENTREQUEST = 905,
	COMMON_CLUSTERCLIENTSOCKETCONNECTED = 906,
	COMMON_SOCKETACCEPT = 907,
	COMMON_SOCKETERROR = 908,
	COMMON_SOCKETDATA = 909,
	COMMON_RPCPARAM = 910,
	COMMON_GATEWAY_INIT = 911,
}
