// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: SkynetMessageReceiver.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace SkynetMessageReceiver {

  /// <summary>Holder for reflection information generated from SkynetMessageReceiver.proto</summary>
  public static partial class SkynetMessageReceiverReflection {

    #region Descriptor
    /// <summary>File descriptor for SkynetMessageReceiver.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static SkynetMessageReceiverReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChtTa3luZXRNZXNzYWdlUmVjZWl2ZXIucHJvdG8SFVNreW5ldE1lc3NhZ2VS",
            "ZWNlaXZlciJVCiZTa3luZXRNZXNzYWdlUmVjZWl2ZXJfT25Qcm9jZXNzUmVx",
            "dWVzdBIVCg1yZXF1ZXN0X2NvdW50GAEgASgFEhQKDHJlcXVlc3RfdGV4dBgC",
            "IAEoCSJdCi5Ta3luZXRNZXNzYWdlUmVjZWl2ZXJfT25Qcm9jZXNzUmVxdWVz",
            "dFJlc3BvbnNlEhUKDXJlcXVlc3RfY291bnQYASABKAUSFAoMcmVxdWVzdF90",
            "ZXh0GAIgASgJYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::SkynetMessageReceiver.SkynetMessageReceiver_OnProcessRequest), global::SkynetMessageReceiver.SkynetMessageReceiver_OnProcessRequest.Parser, new[]{ "RequestCount", "RequestText" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::SkynetMessageReceiver.SkynetMessageReceiver_OnProcessRequestResponse), global::SkynetMessageReceiver.SkynetMessageReceiver_OnProcessRequestResponse.Parser, new[]{ "RequestCount", "RequestText" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class SkynetMessageReceiver_OnProcessRequest : pb::IMessage<SkynetMessageReceiver_OnProcessRequest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<SkynetMessageReceiver_OnProcessRequest> _parser = new pb::MessageParser<SkynetMessageReceiver_OnProcessRequest>(() => new SkynetMessageReceiver_OnProcessRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<SkynetMessageReceiver_OnProcessRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::SkynetMessageReceiver.SkynetMessageReceiverReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SkynetMessageReceiver_OnProcessRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SkynetMessageReceiver_OnProcessRequest(SkynetMessageReceiver_OnProcessRequest other) : this() {
      requestCount_ = other.requestCount_;
      requestText_ = other.requestText_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SkynetMessageReceiver_OnProcessRequest Clone() {
      return new SkynetMessageReceiver_OnProcessRequest(this);
    }

    /// <summary>Field number for the "request_count" field.</summary>
    public const int RequestCountFieldNumber = 1;
    private int requestCount_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int RequestCount {
      get { return requestCount_; }
      set {
        requestCount_ = value;
      }
    }

    /// <summary>Field number for the "request_text" field.</summary>
    public const int RequestTextFieldNumber = 2;
    private string requestText_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string RequestText {
      get { return requestText_; }
      set {
        requestText_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as SkynetMessageReceiver_OnProcessRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(SkynetMessageReceiver_OnProcessRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (RequestCount != other.RequestCount) return false;
      if (RequestText != other.RequestText) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (RequestCount != 0) hash ^= RequestCount.GetHashCode();
      if (RequestText.Length != 0) hash ^= RequestText.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (RequestCount != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(RequestCount);
      }
      if (RequestText.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(RequestText);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (RequestCount != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(RequestCount);
      }
      if (RequestText.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(RequestText);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (RequestCount != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(RequestCount);
      }
      if (RequestText.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(RequestText);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(SkynetMessageReceiver_OnProcessRequest other) {
      if (other == null) {
        return;
      }
      if (other.RequestCount != 0) {
        RequestCount = other.RequestCount;
      }
      if (other.RequestText.Length != 0) {
        RequestText = other.RequestText;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            RequestCount = input.ReadInt32();
            break;
          }
          case 18: {
            RequestText = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            RequestCount = input.ReadInt32();
            break;
          }
          case 18: {
            RequestText = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class SkynetMessageReceiver_OnProcessRequestResponse : pb::IMessage<SkynetMessageReceiver_OnProcessRequestResponse>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<SkynetMessageReceiver_OnProcessRequestResponse> _parser = new pb::MessageParser<SkynetMessageReceiver_OnProcessRequestResponse>(() => new SkynetMessageReceiver_OnProcessRequestResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<SkynetMessageReceiver_OnProcessRequestResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::SkynetMessageReceiver.SkynetMessageReceiverReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SkynetMessageReceiver_OnProcessRequestResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SkynetMessageReceiver_OnProcessRequestResponse(SkynetMessageReceiver_OnProcessRequestResponse other) : this() {
      requestCount_ = other.requestCount_;
      requestText_ = other.requestText_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SkynetMessageReceiver_OnProcessRequestResponse Clone() {
      return new SkynetMessageReceiver_OnProcessRequestResponse(this);
    }

    /// <summary>Field number for the "request_count" field.</summary>
    public const int RequestCountFieldNumber = 1;
    private int requestCount_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int RequestCount {
      get { return requestCount_; }
      set {
        requestCount_ = value;
      }
    }

    /// <summary>Field number for the "request_text" field.</summary>
    public const int RequestTextFieldNumber = 2;
    private string requestText_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string RequestText {
      get { return requestText_; }
      set {
        requestText_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as SkynetMessageReceiver_OnProcessRequestResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(SkynetMessageReceiver_OnProcessRequestResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (RequestCount != other.RequestCount) return false;
      if (RequestText != other.RequestText) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (RequestCount != 0) hash ^= RequestCount.GetHashCode();
      if (RequestText.Length != 0) hash ^= RequestText.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (RequestCount != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(RequestCount);
      }
      if (RequestText.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(RequestText);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (RequestCount != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(RequestCount);
      }
      if (RequestText.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(RequestText);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (RequestCount != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(RequestCount);
      }
      if (RequestText.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(RequestText);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(SkynetMessageReceiver_OnProcessRequestResponse other) {
      if (other == null) {
        return;
      }
      if (other.RequestCount != 0) {
        RequestCount = other.RequestCount;
      }
      if (other.RequestText.Length != 0) {
        RequestText = other.RequestText;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            RequestCount = input.ReadInt32();
            break;
          }
          case 18: {
            RequestText = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            RequestCount = input.ReadInt32();
            break;
          }
          case 18: {
            RequestText = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
